PROTOCOL_VERSION = 340
MC_VERSION = "1.12.2"

CLIENTBOUND = {
    "0": "Spawn Object",
    "1": "Spawn Experience Orb",
    "2": "Spawn Global Entity",
    "3": "Spawn Mob",
    "4": "Spawn Painting",
    "5": "Spawn Player",
    "6": "Animation (clientbound)",
    "7": "Statistics",
    "8": "Block Break Animation",
    "9": "Update Block Entity",
    "10": "Block Action",
    "11": "Block Change",
    "12": "Boss Bar",
    "13": "Server Difficulty",
    "14": "Tab-Complete (clientbound)",
    "15": "Chat Message (clientbound)",
    "16": "Multi Block Change",
    "17": "Confirm Transaction (clientbound)",
    "18": "Close Window (clientbound)",
    "19": "Open Window",
    "20": "Window Items",
    "21": "Window Property",
    "22": "Set Slot",
    "23": "Set Cooldown",
    "24": "Plugin Message (clientbound)",
    "25": "Named Sound Effect",
    "26": "Disconnect (play)",
    "27": "Entity Status",
    "28": "Explosion",
    "29": "Unload Chunk",
    "30": "Change Game State",
    "31": "Keep Alive (clientbound)",
    "32": "Chunk Data",
    "33": "Effect",
    "34": "Particle",
    "35": "Join Game",
    "36": "Map",
    "37": "Entity",
    "38": "Entity Relative Move",
    "39": "Entity Look And Relative Move",
    "40": "Entity Look",
    "41": "Vehicle Move (clientbound)",
    "42": "Open Sign Editor",
    "43": "Craft Recipe Response",
    "44": "Player Abilities (clientbound)",
    "45": "Combat Event",
    "46": "Player List Item",
    "47": "Player Position And Look (clientbound)",
    "48": "Use Bed",
    "49": "Unlock Recipes",
    "50": "Destroy Entities",
    "51": "Remove Entity Effect",
    "52": "Resource Pack Send",
    "53": "Respawn",
    "54": "Entity Head Look",
    "55": "Select Advancement Tab",
    "56": "World Border",
    "57": "Camera",
    "58": "Held Item Change (clientbound)",
    "59": "Display Scoreboard",
    "60": "Entity Metadata",
    "61": "Attach Entity",
    "62": "Entity Velocity",
    "63": "Entity Equipment",
    "64": "Set Experience",
    "65": "Update Health",
    "66": "Scoreboard Objective",
    "67": "Set Passengers",
    "68": "Teams",
    "69": "Update Score",
    "70": "Spawn Position",
    "71": "Time Update",
    "72": "Title",
    "73": "Sound Effect",
    "74": "Player List Header And Footer",
    "75": "Collect Item",
    "76": "Entity Teleport",
    "77": "Advancements",
    "78": "Entity Properties",
    "79": "Entity Effect"
}

SERVERBOUND = {
    "Teleport Confirm": 0,
    "Tab-Complete (serverbound)": 1,
    "Chat Message (serverbound)": 2,
    "Client Status": 3,
    "Client Settings": 4,
    "Confirm Transaction (serverbound)": 5,
    "Enchant Item": 6,
    "Click Window": 7,
    "Close Window (serverbound)": 8,
    "Plugin Message (serverbound)": 9,
    "Use Entity": 10,
    "Keep Alive (serverbound)": 11,
    "Player": 12,
    "Player Position": 13,
    "Player Position And Look (serverbound)": 14,
    "Player Look": 15,
    "Vehicle Move (serverbound)": 16,
    "Steer Boat": 17,
    "Pick Item": 18,
    "Craft Recipe Request": 19,
    "Player Abilities (serverbound)": 20,
    "Player Digging": 21,
    "Entity Action": 22,
    "Steer Vehicle": 23,
    "Recipe Book Data": 24,
    "Resource Pack Status": 25,
    "Advancement Tab": 26,
    "Held Item Change (serverbound)": 27,
    "Creative Inventory Action": 28,
    "Update Sign": 29,
    "Animation (serverbound)": 30,
    "Spectate": 31,
    "Player Block Placement": 32,
    "Use Item": 33
}

METADATA_FILE_FORMAT = 9
